applications:
  - key: bookverse-recommendations
    seeds:
      application: 4.1.18
    packages:
      - type: docker
        name: recommendations
        seed: 2.7.14
      - type: docker
        name: recommendations-worker
        seed: 1.8.22
      - type: generic
        name: recommendation-config
        seed: 1.13.43
      - type: generic
        name: resources
        seed: 5.9.42
