applications:
  - key: bookverse-recommendations
    seeds:
      application: 1.12.4
      build: 2.9.18
    packages:
      - type: docker
        name: recommendations-api
        seed: 2.10.5
      - type: docker
        name: recommendations-worker
        seed: 1.4.22
