applications:
  - key: bookverse-recommendations
    seeds:
      application: 4.1.18
      build: 5.3.29
    packages:
      - type: docker
        name: recommendations
        seed: 2.7.14
      - type: docker
        name: recommendations-worker
        seed: 1.8.22
