name: Promote (standard)

on:
  workflow_dispatch:
    inputs:
      target_stage:
        description: 'Target stage (DEV, QA, STAGING, PROD)'
        required: true
        type: choice
        default: 'PROD'
        options:
          - DEV
          - QA
          - STAGING
          - PROD
      version:
        description: 'Application version (SemVer). If empty, use latest.'
        required: false
        type: string
      DEMO_MODE:
        description: 'Enable demo mode (verbose logs, request tracing)'
        required: false
        default: 'false'
        type: choice
        options: ['false', 'true']

jobs:
  promote:
    uses: ./.github/workflows/promote.reusable.yml
    with:
      target_stage: ${{ inputs.target_stage }}
      application_version: ${{ inputs.version }}
      DEMO_MODE: ${{ inputs.DEMO_MODE }}
      service_name: recommendations
      oidc_provider_name: bookverse-recommendations-github
      evidence_key_alias: ${{ vars.EVIDENCE_KEY_ALIAS }}
    secrets: inherit


